"""Shared typed boundaries for onboard, simulation, and cloud services."""

from __future__ import annotations

from greenhouse_contracts.follow import (
    BoundingBoxNormalized,
    EmbeddingVector,
    FollowCommandAccepted,
    FollowController,
    FollowGoal,
    PersonDetector,
    PersonObservation,
    PersonReIdentifier,
    RankedObservation,
)
from greenhouse_contracts.geometry import Pose2D, Twist2D
from greenhouse_contracts.identifiers import RobotIdField
from greenhouse_contracts.localization import (
    LocalizationEstimate,
    LocalizationSnapshot,
    LocalizationStatus,
    Localizer,
)
from greenhouse_contracts.mapping import (
    MapBuilder,
    MapExtents,
    MapSessionResult,
    MapStore,
    PersistedMap,
    PersistMapResult,
)
from greenhouse_contracts.messaging import (
    MQTT_TOPIC_PREFIX,
    AckStatus,
    BeginFollow,
    CancelActiveMission,
    CommandAck,
    CommandPayloadUnion,
    EmergencyStop,
    IncomingCommandEnvelope,
    NavigateToPose,
    RobotMode,
    StartMapping,
    StopMapping,
    TelemetryEnvelope,
    command_ack_topic,
    commands_topic,
    robot_base_topic,
    telemetry_topic,
)
from greenhouse_contracts.motion import MotionController
from greenhouse_contracts.navigation import (
    GoalNavigator,
    NavigationCancellation,
    NavigationFailure,
    NavigationResult,
    NavigationSuccess,
    PathPlanner,
    PathSegment,
    PlanningOutcome,
    PlanningUnavailable,
)
from greenhouse_contracts.orchestration import MissionHandler, RobotBehavior
from greenhouse_contracts.perception import (
    CameraFrame,
    CameraSource,
    ImuSample,
    ImuSource,
    LaserScan,
    LidarSource,
)
from greenhouse_contracts.telemetry_bridge import (
    CommandDispatchHandler,
    CommandSubscriber,
    TelemetryDispatchResult,
    TelemetryPublisher,
)

__all__ = [
    "AckStatus",
    "BeginFollow",
    "BoundingBoxNormalized",
    "CancelActiveMission",
    "CameraFrame",
    "CameraSource",
    "CommandAck",
    "CommandDispatchHandler",
    "CommandPayloadUnion",
    "CommandSubscriber",
    "EmergencyStop",
    "EmbeddingVector",
    "FollowCommandAccepted",
    "FollowController",
    "FollowGoal",
    "GoalNavigator",
    "ImuSample",
    "ImuSource",
    "IncomingCommandEnvelope",
    "LaserScan",
    "LidarSource",
    "Localizer",
    "LocalizationEstimate",
    "LocalizationSnapshot",
    "LocalizationStatus",
    "MapBuilder",
    "MapExtents",
    "MapSessionResult",
    "MapStore",
    "MQTT_TOPIC_PREFIX",
    "MissionHandler",
    "MotionController",
    "NavigateToPose",
    "NavigationCancellation",
    "NavigationFailure",
    "NavigationResult",
    "NavigationSuccess",
    "PathPlanner",
    "PathSegment",
    "PersistMapResult",
    "PersistedMap",
    "PersonDetector",
    "PersonObservation",
    "PersonReIdentifier",
    "PlanningOutcome",
    "PlanningUnavailable",
    "Pose2D",
    "RankedObservation",
    "RobotBehavior",
    "RobotIdField",
    "RobotMode",
    "StartMapping",
    "StopMapping",
    "TelemetryDispatchResult",
    "TelemetryEnvelope",
    "TelemetryPublisher",
    "Twist2D",
    "command_ack_topic",
    "commands_topic",
    "robot_base_topic",
    "telemetry_topic",
]
